//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.Shared.Translations.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Field_OfficialName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Field_OfficialName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.Shared.Translations.Enum.Field_OfficialName", typeof(Field_OfficialName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Connectivity Index (International Air Transport Association).
        /// </summary>
        public static string AirConnectivityIndex {
            get {
                return ResourceManager.GetString("AirConnectivityIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Air Quality Report (IQAir).
        /// </summary>
        public static string AirQuality {
            get {
                return ResourceManager.GetString("AirQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average annual surface temperature (World Bank Group).
        /// </summary>
        public static string AnnualTemperature {
            get {
                return ResourceManager.GetString("AnnualTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Index (FOREX).
        /// </summary>
        public static string CashlessIndex {
            get {
                return ResourceManager.GetString("CashlessIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index on Censorship.
        /// </summary>
        public static string CensorshipIndex {
            get {
                return ResourceManager.GetString("CensorshipIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corruption Perceptions Index (Transparency International).
        /// </summary>
        public static string CorruptionScore {
            get {
                return ResourceManager.GetString("CorruptionScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality of Democracy (Democracy Matrix).
        /// </summary>
        public static string DMDemocracyIndex {
            get {
                return ResourceManager.GetString("DMDemocracyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of Economic Freedom (The Heritage Foundation).
        /// </summary>
        public static string EconomicFreedomIndex {
            get {
                return ResourceManager.GetString("EconomicFreedomIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Democracy Index (The Economist).
        /// </summary>
        public static string EconomistDemocracyIndex {
            get {
                return ResourceManager.GetString("EconomistDemocracyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freedom of Expression Index (Varieties of Democracy).
        /// </summary>
        public static string FreedomExpressionIndex {
            get {
                return ResourceManager.GetString("FreedomExpressionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freedom in the World Score (Freedom House).
        /// </summary>
        public static string FreedomScore {
            get {
                return ResourceManager.GetString("FreedomScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDP (Gross Domestic Product) per capita - Nominal.
        /// </summary>
        public static string GDP_Nominal {
            get {
                return ResourceManager.GetString("GDP_Nominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDP (Gross Domestic Product) per capita - PPP.
        /// </summary>
        public static string GDP_PPP {
            get {
                return ResourceManager.GetString("GDP_PPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Peace Index (Vision of Humanity).
        /// </summary>
        public static string GlobalPeaceIndex {
            get {
                return ResourceManager.GetString("GlobalPeaceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Terrorism Index (Vision of Humanity).
        /// </summary>
        public static string GlobalTerrorismIndex {
            get {
                return ResourceManager.GetString("GlobalTerrorismIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Happiness Report.
        /// </summary>
        public static string HappinessIndex {
            get {
                return ResourceManager.GetString("HappinessIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Development Index (Human Development Reports).
        /// </summary>
        public static string HDI {
            get {
                return ResourceManager.GetString("HDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Care Index (CEOWORLD).
        /// </summary>
        public static string HealthCareIndex {
            get {
                return ResourceManager.GetString("HealthCareIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Index (Numbeo).
        /// </summary>
        public static string NumbeoPollutionIndex {
            get {
                return ResourceManager.GetString("NumbeoPollutionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Index (Numbeo).
        /// </summary>
        public static string NumbeoSafetyIndex {
            get {
                return ResourceManager.GetString("NumbeoSafetyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Organisation for Economic Co-operation and Development.
        /// </summary>
        public static string OECD {
            get {
                return ResourceManager.GetString("OECD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Sustainable Mobility Index (GSMI - SuM4All).
        /// </summary>
        public static string SustainableMobilityIndex {
            get {
                return ResourceManager.GetString("SustainableMobilityIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel &amp; Tourism Development Index (World Economic Forum).
        /// </summary>
        public static string TourismIndex {
            get {
                return ResourceManager.GetString("TourismIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Index (Travel Safe - Abroad).
        /// </summary>
        public static string TsaSafetyIndex {
            get {
                return ResourceManager.GetString("TsaSafetyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Henley Passport Index (Henley &amp; Partners).
        /// </summary>
        public static string VisaFree {
            get {
                return ResourceManager.GetString("VisaFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitation &amp; Drinking Water Score (Environmental Performance Index - Yale).
        /// </summary>
        public static string YaleWaterScore {
            get {
                return ResourceManager.GetString("YaleWaterScore", resourceCulture);
            }
        }
    }
}
