//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.Shared.Translations.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Religion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Religion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.Shared.Translations.Enum.Religion", typeof(Religion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddhists.
        /// </summary>
        public static string Buddhists {
            get {
                return ResourceManager.GetString("Buddhists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christians.
        /// </summary>
        public static string Christians {
            get {
                return ResourceManager.GetString("Christians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindus.
        /// </summary>
        public static string Hindus {
            get {
                return ResourceManager.GetString("Hindus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jews.
        /// </summary>
        public static string Jews {
            get {
                return ResourceManager.GetString("Jews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslims.
        /// </summary>
        public static string Muslims {
            get {
                return ResourceManager.GetString("Muslims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Religions.
        /// </summary>
        public static string OtherReligions {
            get {
                return ResourceManager.GetString("OtherReligions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unaffiliated.
        /// </summary>
        public static string Unaffiliated {
            get {
                return ResourceManager.GetString("Unaffiliated", resourceCulture);
            }
        }
    }
}
