//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Field {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Field() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.Shared.Resources.Enum.Field", typeof(Field).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Accommodation.
        /// </summary>
        public static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It measures how connected a country is to global air travel, showing access to destinations and international mobility..
        /// </summary>
        public static string AirConnectivityIndexDesc {
            get {
                return ResourceManager.GetString("AirConnectivityIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It shows how clean or polluted the air people breathe daily is, helping to understand the impacts on health, well-being, and quality of life..
        /// </summary>
        public static string AirQualityDesc {
            get {
                return ResourceManager.GetString("AirQualityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambulance.
        /// </summary>
        public static string Ambulance {
            get {
                return ResourceManager.GetString("Ambulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It shows the average temperature throughout the year in a country, helping to understand the prevailing climate and thermal comfort for living or traveling..
        /// </summary>
        public static string AnnualTemperatureDesc {
            get {
                return ResourceManager.GetString("AnnualTemperatureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renting (Center).
        /// </summary>
        public static string AptCityCenter {
            get {
                return ResourceManager.GetString("AptCityCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment (1 bedroom, City Center).
        /// </summary>
        public static string AptCityCenterDesc {
            get {
                return ResourceManager.GetString("AptCityCenterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renting (Suburb).
        /// </summary>
        public static string AptOutsideCenter {
            get {
                return ResourceManager.GetString("AptOutsideCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment (1 bedroom, Outside of Center).
        /// </summary>
        public static string AptOutsideCenterDesc {
            get {
                return ResourceManager.GetString("AptOutsideCenterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband.
        /// </summary>
        public static string BroadbandSpeed {
            get {
                return ResourceManager.GetString("BroadbandSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Gains.
        /// </summary>
        public static string CapitalGains {
            get {
                return ResourceManager.GetString("CapitalGains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures how free people are to access and share information, including the extent of restrictions on media, ideas, and online content..
        /// </summary>
        public static string CensorshipIndexDesc {
            get {
                return ResourceManager.GetString("CensorshipIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Level.
        /// </summary>
        public static string ConflictLevel {
            get {
                return ResourceManager.GetString("ConflictLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts.
        /// </summary>
        public static string Conflicts {
            get {
                return ResourceManager.GetString("Conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string Corporate {
            get {
                return ResourceManager.GetString("Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how honest people believe their leaders and public officials are, helping to understand how trust and fairness work in a country..
        /// </summary>
        public static string CorruptionScoreDesc {
            get {
                return ResourceManager.GetString("CorruptionScoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluates how open and fair a country&apos;s political system is, including how people participate in choosing leaders and influencing decisions..
        /// </summary>
        public static string DMDemocracyIndexDesc {
            get {
                return ResourceManager.GetString("DMDemocracyIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates how much people and businesses can make economic choices freely, including starting businesses, trading, and using resources, which affects growth and prosperity..
        /// </summary>
        public static string EconomicFreedomIndexDesc {
            get {
                return ResourceManager.GetString("EconomicFreedomIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures how well citizens can vote, express opinions freely, enjoy rights, and participate in a government that is accountable and fair..
        /// </summary>
        public static string EconomistDemocracyIndexDesc {
            get {
                return ResourceManager.GetString("EconomistDemocracyIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Numbers.
        /// </summary>
        public static string EmergencyNumbers {
            get {
                return ResourceManager.GetString("EmergencyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates how freely people can discuss ideas, politics, and culture, and how independent media and educational spaces are in sharing opinions..
        /// </summary>
        public static string FreedomExpressionIndexDesc {
            get {
                return ResourceManager.GetString("FreedomExpressionIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how much political rights and civil liberties people enjoy, including voting, speaking freely, and participating in society without fear..
        /// </summary>
        public static string FreedomScoreDesc {
            get {
                return ResourceManager.GetString("FreedomScoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the total value of goods and services produced per person in a country, measured in current US dollars, helping to compare countries&apos; economies globally..
        /// </summary>
        public static string GDP_NominalDesc {
            get {
                return ResourceManager.GetString("GDP_NominalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures the average economic output per person in a country, adjusted for differences in cost of living, showing how much people can buy and their relative standard of living..
        /// </summary>
        public static string GDP_PPPDesc {
            get {
                return ResourceManager.GetString("GDP_PPPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates how peaceful a country is, considering safety, conflict levels, and social stability, to show how calm or tense life can be in that country..
        /// </summary>
        public static string GlobalPeaceIndexDesc {
            get {
                return ResourceManager.GetString("GlobalPeaceIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures the impact of terrorism on a country, including incidents, injuries, and fatalities, giving a sense of how likely such events are to affect daily life..
        /// </summary>
        public static string GlobalTerrorismIndexDesc {
            get {
                return ResourceManager.GetString("GlobalTerrorismIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates how happy people feel in their daily life, considering their well-being, opportunities, community, and quality of life..
        /// </summary>
        public static string HappinessIndexDesc {
            get {
                return ResourceManager.GetString("HappinessIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures how well people can live healthy lives, gain education, and have a decent standard of living, showing overall human development..
        /// </summary>
        public static string HDIDesc {
            get {
                return ResourceManager.GetString("HDIDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It assesses the quality of and access to a country&apos;s health services, including factors such as medical infrastructure, care, and availability of professionals..
        /// </summary>
        public static string HealthCareIndexDesc {
            get {
                return ResourceManager.GetString("HealthCareIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel or health insurance.
        /// </summary>
        public static string HealthInsurance {
            get {
                return ResourceManager.GetString("HealthInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income (Highest).
        /// </summary>
        public static string IncomeHighest {
            get {
                return ResourceManager.GetString("IncomeHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income (Lowest).
        /// </summary>
        public static string IncomeLowest {
            get {
                return ResourceManager.GetString("IncomeLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance / Estate.
        /// </summary>
        public static string InheritanceEstate {
            get {
                return ResourceManager.GetString("InheritanceEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market (Asian).
        /// </summary>
        public static string MarketAsian {
            get {
                return ResourceManager.GetString("MarketAsian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market (2400 calories, Asian food types).
        /// </summary>
        public static string MarketAsianDesc {
            get {
                return ResourceManager.GetString("MarketAsianDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market (Western).
        /// </summary>
        public static string MarketWestern {
            get {
                return ResourceManager.GetString("MarketWestern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market (2400 calories, Western food types).
        /// </summary>
        public static string MarketWesternDesc {
            get {
                return ResourceManager.GetString("MarketWesternDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal.
        /// </summary>
        public static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal (Inexpensive Restaurant).
        /// </summary>
        public static string MealDesc {
            get {
                return ResourceManager.GetString("MealDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory proof of minimum funds.
        /// </summary>
        public static string MinimumFunds {
            get {
                return ResourceManager.GetString("MinimumFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mugging.
        /// </summary>
        public static string Mugging {
            get {
                return ResourceManager.GetString("Mugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Disasters.
        /// </summary>
        public static string NaturalDisasters {
            get {
                return ResourceManager.GetString("NaturalDisasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the level of pollution in a city or country, including air, water, noise, waste, and overall cleanliness, helping to understand how healthy the environment is..
        /// </summary>
        public static string NumbeoPollutionIndexDesc {
            get {
                return ResourceManager.GetString("NumbeoPollutionIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimates the overall level of crime in a city or country, helping to understand how safe everyday life is for residents and visitors..
        /// </summary>
        public static string NumbeoSafetyIndexDesc {
            get {
                return ResourceManager.GetString("NumbeoSafetyIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows whether a country is part of an international group where nations share knowledge, ideas, and strategies to improve public policies and economic practices..
        /// </summary>
        public static string OECDDesc {
            get {
                return ResourceManager.GetString("OECDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickpockets.
        /// </summary>
        public static string Pickpockets {
            get {
                return ResourceManager.GetString("Pickpockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police.
        /// </summary>
        public static string Police {
            get {
                return ResourceManager.GetString("Police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Return or Onward Ticket.
        /// </summary>
        public static string ReturnTicket {
            get {
                return ResourceManager.GetString("ReturnTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks.
        /// </summary>
        public static string Risks {
            get {
                return ResourceManager.GetString("Risks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scams.
        /// </summary>
        public static string Scams {
            get {
                return ResourceManager.GetString("Scams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It assesses how efficiently, safely, and sustainably people can move, considering transport access and mobility quality..
        /// </summary>
        public static string SustainableMobilityIndexDesc {
            get {
                return ResourceManager.GetString("SustainableMobilityIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap Water.
        /// </summary>
        public static string TapWater {
            get {
                return ResourceManager.GetString("TapWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi Apps.
        /// </summary>
        public static string TaxiApps {
            get {
                return ResourceManager.GetString("TaxiApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorism.
        /// </summary>
        public static string Terrorism {
            get {
                return ResourceManager.GetString("Terrorism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipping.
        /// </summary>
        public static string Tipping {
            get {
                return ResourceManager.GetString("Tipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures how well a country supports travel and tourism, including facilities, policies, and opportunities, showing how easy and enjoyable it is to visit..
        /// </summary>
        public static string TourismIndexDesc {
            get {
                return ResourceManager.GetString("TourismIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport &amp; Taxis.
        /// </summary>
        public static string TransportTaxis {
            get {
                return ResourceManager.GetString("TransportTaxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Requirements.
        /// </summary>
        public static string TravelRequirements {
            get {
                return ResourceManager.GetString("TravelRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how safe it is for people to live or travel in a country, taking into account risks such as crime, property theft, social tensions, and general public safety..
        /// </summary>
        public static string TsaSafetyIndexDesc {
            get {
                return ResourceManager.GetString("TsaSafetyIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT / GST / Sales.
        /// </summary>
        public static string VATGSTSales {
            get {
                return ResourceManager.GetString("VATGSTSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how many countries a passport holder can visit without needing a visa, indicating travel freedom and ease of international mobility..
        /// </summary>
        public static string VisaFreeDesc {
            get {
                return ResourceManager.GetString("VisaFreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These requirements represent the most common travel rules for this country. Actual requirements may vary depending on your passport, visa type, places visited, or length of stay..
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth.
        /// </summary>
        public static string Wealth {
            get {
                return ResourceManager.GetString("Wealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women Travelers.
        /// </summary>
        public static string WomenTravelers {
            get {
                return ResourceManager.GetString("WomenTravelers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how well a country provides clean drinking water and proper sanitation, helping people stay healthy and avoid diseases..
        /// </summary>
        public static string YaleWaterScoreDesc {
            get {
                return ResourceManager.GetString("YaleWaterScoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Yellow Fever Vaccination.
        /// </summary>
        public static string YellowFever {
            get {
                return ResourceManager.GetString("YellowFever", resourceCulture);
            }
        }
    }
}
