//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuggestionEnum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuggestionEnum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.Shared.Resources.Enum.SuggestionEnum", typeof(SuggestionEnum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the world’s top countries for adventure tourism, ranked by landscapes, outdoor activities, safety, and infrastructure for thrilling experiences..
        /// </summary>
        public static string AdventureDescription {
            get {
                return ResourceManager.GetString("AdventureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string AdventureShort {
            get {
                return ResourceManager.GetString("AdventureShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdventureSubtitle {
            get {
                return ResourceManager.GetString("AdventureSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The World’s Best Countries For Adventure Tourism.
        /// </summary>
        public static string AdventureTitle {
            get {
                return ResourceManager.GetString("AdventureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in April worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string AprilDescription {
            get {
                return ResourceManager.GetString("AprilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string AprilShort {
            get {
                return ResourceManager.GetString("AprilShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AprilSubtitle {
            get {
                return ResourceManager.GetString("AprilSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in April.
        /// </summary>
        public static string AprilTitle {
            get {
                return ResourceManager.GetString("AprilTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in August worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string AugustDescription {
            get {
                return ResourceManager.GetString("AugustDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string AugustShort {
            get {
                return ResourceManager.GetString("AugustShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AugustSubtitle {
            get {
                return ResourceManager.GetString("AugustSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in August.
        /// </summary>
        public static string AugustTitle {
            get {
                return ResourceManager.GetString("AugustTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the world’s top beach destinations, recognized by travelers for stunning shores, crystal waters, and unforgettable coastal experiences..
        /// </summary>
        public static string BeachLoversDescription {
            get {
                return ResourceManager.GetString("BeachLoversDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach Lovers.
        /// </summary>
        public static string BeachLoversShort {
            get {
                return ResourceManager.GetString("BeachLoversShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripadvisor - Travelers’ Choice Awards.
        /// </summary>
        public static string BeachLoversSubtitle {
            get {
                return ResourceManager.GetString("BeachLoversSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best destinations for beach lovers.
        /// </summary>
        public static string BeachLoversTitle {
            get {
                return ResourceManager.GetString("BeachLoversTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the world’s top countries for culture and heritage, ranked by historical sites, traditions, iconic cuisine, and cultural attractions..
        /// </summary>
        public static string CulturalDescription {
            get {
                return ResourceManager.GetString("CulturalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural &amp; Heritage.
        /// </summary>
        public static string CulturalShort {
            get {
                return ResourceManager.GetString("CulturalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CulturalSubtitle {
            get {
                return ResourceManager.GetString("CulturalSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Countries for Culture and Heritage.
        /// </summary>
        public static string CulturalTitle {
            get {
                return ResourceManager.GetString("CulturalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in December worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string DecemberDescription {
            get {
                return ResourceManager.GetString("DecemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string DecemberShort {
            get {
                return ResourceManager.GetString("DecemberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DecemberSubtitle {
            get {
                return ResourceManager.GetString("DecemberSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in December.
        /// </summary>
        public static string DecemberTitle {
            get {
                return ResourceManager.GetString("DecemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best cities for digital nomads, offering reliable infrastructure, vibrant communities, and ideal environments for remote work and travel..
        /// </summary>
        public static string DigitalNomadDescription {
            get {
                return ResourceManager.GetString("DigitalNomadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Nomad.
        /// </summary>
        public static string DigitalNomadShort {
            get {
                return ResourceManager.GetString("DigitalNomadShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DigitalNomadSubtitle {
            get {
                return ResourceManager.GetString("DigitalNomadSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best cities for digital nomads.
        /// </summary>
        public static string DigitalNomadTitle {
            get {
                return ResourceManager.GetString("DigitalNomadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in February worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string FebruaryDescription {
            get {
                return ResourceManager.GetString("FebruaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string FebruaryShort {
            get {
                return ResourceManager.GetString("FebruaryShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FebruarySubtitle {
            get {
                return ResourceManager.GetString("FebruarySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in February.
        /// </summary>
        public static string FebruaryTitle {
            get {
                return ResourceManager.GetString("FebruaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the top destinations for food lovers, ranked for exceptional cuisine, local specialties, and unforgettable culinary experiences worldwide..
        /// </summary>
        public static string FoodLoversDescription {
            get {
                return ResourceManager.GetString("FoodLoversDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Lovers.
        /// </summary>
        public static string FoodLoversShort {
            get {
                return ResourceManager.GetString("FoodLoversShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michelin Guide.
        /// </summary>
        public static string FoodLoversSubtitle {
            get {
                return ResourceManager.GetString("FoodLoversSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best destinations for Food Lovers.
        /// </summary>
        public static string FoodLoversTitle {
            get {
                return ResourceManager.GetString("FoodLoversTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha level cities are linked to major economic states/regions and highly integrated into the world economy..
        /// </summary>
        public static string GlobalCitiesAlphaDescription {
            get {
                return ResourceManager.GetString("GlobalCitiesAlphaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GlobalCitiesAlphaSubtitle {
            get {
                return ResourceManager.GetString("GlobalCitiesAlphaSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Cities (Alpha Level).
        /// </summary>
        public static string GlobalCitiesAlphaTitle {
            get {
                return ResourceManager.GetString("GlobalCitiesAlphaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta level cities are cities that link moderate economic regions to the world economy..
        /// </summary>
        public static string GlobalCitiesBetaDescription {
            get {
                return ResourceManager.GetString("GlobalCitiesBetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GlobalCitiesBetaSubtitle {
            get {
                return ResourceManager.GetString("GlobalCitiesBetaSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Cities (Beta Level).
        /// </summary>
        public static string GlobalCitiesBetaTitle {
            get {
                return ResourceManager.GetString("GlobalCitiesBetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma level cities are cities that link smaller economic regions into the world economy..
        /// </summary>
        public static string GlobalCitiesGammaDescription {
            get {
                return ResourceManager.GetString("GlobalCitiesGammaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GlobalCitiesGammaSubtitle {
            get {
                return ResourceManager.GetString("GlobalCitiesGammaSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Cities (Gamma Level).
        /// </summary>
        public static string GlobalCitiesGammaTitle {
            get {
                return ResourceManager.GetString("GlobalCitiesGammaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufficiency level cities are cities that have a sufficient degree of services so as not to be overly dependent on world cities..
        /// </summary>
        public static string GlobalCitiesSufficiencyDescription {
            get {
                return ResourceManager.GetString("GlobalCitiesSufficiencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GlobalCitiesSufficiencySubtitle {
            get {
                return ResourceManager.GetString("GlobalCitiesSufficiencySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Cities (Sufficiency Level).
        /// </summary>
        public static string GlobalCitiesSufficiencyTitle {
            get {
                return ResourceManager.GetString("GlobalCitiesSufficiencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the world’s top honeymoon destinations, recognized by travelers for romance, beauty, and unforgettable experiences..
        /// </summary>
        public static string HoneymoonDescription {
            get {
                return ResourceManager.GetString("HoneymoonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honeymoon.
        /// </summary>
        public static string HoneymoonShort {
            get {
                return ResourceManager.GetString("HoneymoonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripadvisor - Travelers’ Choice Awards.
        /// </summary>
        public static string HoneymoonSubtitle {
            get {
                return ResourceManager.GetString("HoneymoonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best cities for a honeymoon.
        /// </summary>
        public static string HoneymoonTitle {
            get {
                return ResourceManager.GetString("HoneymoonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in January worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string JanuaryDescription {
            get {
                return ResourceManager.GetString("JanuaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string JanuaryShort {
            get {
                return ResourceManager.GetString("JanuaryShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JanuarySubtitle {
            get {
                return ResourceManager.GetString("JanuarySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in January.
        /// </summary>
        public static string JanuaryTitle {
            get {
                return ResourceManager.GetString("JanuaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in July worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string JulyDescription {
            get {
                return ResourceManager.GetString("JulyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string JulyShort {
            get {
                return ResourceManager.GetString("JulyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JulySubtitle {
            get {
                return ResourceManager.GetString("JulySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in July.
        /// </summary>
        public static string JulyTitle {
            get {
                return ResourceManager.GetString("JulyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in June worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string JuneDescription {
            get {
                return ResourceManager.GetString("JuneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string JuneShort {
            get {
                return ResourceManager.GetString("JuneShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JuneSubtitle {
            get {
                return ResourceManager.GetString("JuneSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in June.
        /// </summary>
        public static string JuneTitle {
            get {
                return ResourceManager.GetString("JuneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the world’s most beautiful natural landscapes, ranked for scenic quality, breathtaking views, dramatic landforms, and unforgettable beauty..
        /// </summary>
        public static string LandscapeDescription {
            get {
                return ResourceManager.GetString("LandscapeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Landscapes.
        /// </summary>
        public static string LandscapeShort {
            get {
                return ResourceManager.GetString("LandscapeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LandscapeSubtitle {
            get {
                return ResourceManager.GetString("LandscapeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Beautiful Landscapes in the World.
        /// </summary>
        public static string LandscapeTitle {
            get {
                return ResourceManager.GetString("LandscapeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the world’s most luxurious cities, known for premium lifestyle, upscale services, iconic landmarks, and exclusive travel experiences..
        /// </summary>
        public static string LuxuryDescription {
            get {
                return ResourceManager.GetString("LuxuryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxury.
        /// </summary>
        public static string LuxuryShort {
            get {
                return ResourceManager.GetString("LuxuryShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LuxurySubtitle {
            get {
                return ResourceManager.GetString("LuxurySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Luxurious Cities in the World.
        /// </summary>
        public static string LuxuryTitle {
            get {
                return ResourceManager.GetString("LuxuryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in March worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string MarchDescription {
            get {
                return ResourceManager.GetString("MarchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string MarchShort {
            get {
                return ResourceManager.GetString("MarchShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MarchSubtitle {
            get {
                return ResourceManager.GetString("MarchSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in March.
        /// </summary>
        public static string MarchTitle {
            get {
                return ResourceManager.GetString("MarchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in May worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string MayDescription {
            get {
                return ResourceManager.GetString("MayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MayShort {
            get {
                return ResourceManager.GetString("MayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MaySubtitle {
            get {
                return ResourceManager.GetString("MaySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in May.
        /// </summary>
        public static string MayTitle {
            get {
                return ResourceManager.GetString("MayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 100 most visited cities in terms of international tourists per year.
        /// </summary>
        public static string MostVisitedDescription {
            get {
                return ResourceManager.GetString("MostVisitedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MostVisitedShort {
            get {
                return ResourceManager.GetString("MostVisitedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MostVisitedSubtitle {
            get {
                return ResourceManager.GetString("MostVisitedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most visited cities in the world.
        /// </summary>
        public static string MostVisitedTitle {
            get {
                return ResourceManager.GetString("MostVisitedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the world’s top cities for nightlife, known for vibrant bars, clubs, entertainment, and unforgettable evening experiences..
        /// </summary>
        public static string NightlifeDescription {
            get {
                return ResourceManager.GetString("NightlifeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightlife.
        /// </summary>
        public static string NightlifeShort {
            get {
                return ResourceManager.GetString("NightlifeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world’s 20 best cities for nightlife.
        /// </summary>
        public static string NightlifeSubtitle {
            get {
                return ResourceManager.GetString("NightlifeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best cities for nightlife.
        /// </summary>
        public static string NightlifeTitle {
            get {
                return ResourceManager.GetString("NightlifeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in November worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string NovemberDescription {
            get {
                return ResourceManager.GetString("NovemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string NovemberShort {
            get {
                return ResourceManager.GetString("NovemberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NovemberSubtitle {
            get {
                return ResourceManager.GetString("NovemberSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in November.
        /// </summary>
        public static string NovemberTitle {
            get {
                return ResourceManager.GetString("NovemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in October worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string OctoberDescription {
            get {
                return ResourceManager.GetString("OctoberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string OctoberShort {
            get {
                return ResourceManager.GetString("OctoberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OctoberSubtitle {
            get {
                return ResourceManager.GetString("OctoberSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in October.
        /// </summary>
        public static string OctoberTitle {
            get {
                return ResourceManager.GetString("OctoberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the world’s most relaxing destinations, ranked for serenity, safety, nature, low crowds, and top-quality wellness experiences..
        /// </summary>
        public static string RelaxingDescription {
            get {
                return ResourceManager.GetString("RelaxingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaxing.
        /// </summary>
        public static string RelaxingShort {
            get {
                return ResourceManager.GetString("RelaxingShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelaxingSubtitle {
            get {
                return ResourceManager.GetString("RelaxingSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Relaxing Vacation Destinations.
        /// </summary>
        public static string RelaxingTitle {
            get {
                return ResourceManager.GetString("RelaxingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best events in September worldwide, including festivals, cultural celebrations, and local happenings for unforgettable experiences..
        /// </summary>
        public static string SeptemberDescription {
            get {
                return ResourceManager.GetString("SeptemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string SeptemberShort {
            get {
                return ResourceManager.GetString("SeptemberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SeptemberSubtitle {
            get {
                return ResourceManager.GetString("SeptemberSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and festivals in September.
        /// </summary>
        public static string SeptemberTitle {
            get {
                return ResourceManager.GetString("SeptemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the best solo travel destinations, recognized by travelers for safety, experiences, and unforgettable adventures around the world..
        /// </summary>
        public static string SoloDescription {
            get {
                return ResourceManager.GetString("SoloDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Trip.
        /// </summary>
        public static string SoloShort {
            get {
                return ResourceManager.GetString("SoloShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripadvisor - Travelers’ Choice Awards.
        /// </summary>
        public static string SoloSubtitle {
            get {
                return ResourceManager.GetString("SoloSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best cities for a solo trip.
        /// </summary>
        public static string SoloTitle {
            get {
                return ResourceManager.GetString("SoloTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the top-rated destinations worldwide, recognized by travelers in the Tripadvisor Travelers’ Choice Awards for unforgettable experiences..
        /// </summary>
        public static string TopDestinationsDescription {
            get {
                return ResourceManager.GetString("TopDestinationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Destinations.
        /// </summary>
        public static string TopDestinationsShort {
            get {
                return ResourceManager.GetString("TopDestinationsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripadvisor - Travelers’ Choice Awards.
        /// </summary>
        public static string TopDestinationsSubtitle {
            get {
                return ResourceManager.GetString("TopDestinationsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best travel destinations.
        /// </summary>
        public static string TopDestinationsTitle {
            get {
                return ResourceManager.GetString("TopDestinationsTitle", resourceCulture);
            }
        }
    }
}
