//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeoTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeoTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.WEB.Resources.SeoTranslations", typeof(SeoTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore countries and cities, learn interesting facts, and create your profile to find destinations that match your lifestyle, whether for a trip or a new home..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Destinations.
        /// </summary>
        public static string BestDestinations {
            get {
                return ResourceManager.GetString("BestDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive selection from My Next Spot (based on dozens of different indexes and scores).
        /// </summary>
        public static string BestDestinationsDesc {
            get {
                return ResourceManager.GetString("BestDestinationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and Festivals.
        /// </summary>
        public static string EventsFestivals {
            get {
                return ResourceManager.GetString("EventsFestivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover destinations through their events and festivals. Plan your trips around cultural experiences, seasonal celebrations, and local happenings..
        /// </summary>
        public static string EventsFestivalsDesc {
            get {
                return ResourceManager.GetString("EventsFestivalsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover all countries on My Next Spot with their unique global scores, providing a clear overview of safety, economy, environment, and travel potential..
        /// </summary>
        public static string ExploreDesc {
            get {
                return ResourceManager.GetString("ExploreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        public static string HelpCenter {
            get {
                return ResourceManager.GetString("HelpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get detailed guides, troubleshooting tips, FAQs, and contact support for {0}. Solve issues and discover features easily..
        /// </summary>
        public static string HelpCenterDesc {
            get {
                return ResourceManager.GetString("HelpCenterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your favorite streaming providers, wishlists (movies, series and documentaries), what you&apos;re currently watching and much more..
        /// </summary>
        public static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores and Indexes.
        /// </summary>
        public static string ScoresIndexes {
            get {
                return ResourceManager.GetString("ScoresIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare destinations using global scores and indexes. Explore rankings and metrics to evaluate safety, economy, environment, and travel factors..
        /// </summary>
        public static string ScoresIndexesDesc {
            get {
                return ResourceManager.GetString("ScoresIndexesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover travel suggestions on My Next Spot based on themes, interests, events, and destination scores to help you find your next ideal destination..
        /// </summary>
        public static string SuggestionsDesc {
            get {
                return ResourceManager.GetString("SuggestionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes and Interests.
        /// </summary>
        public static string ThemesInterests {
            get {
                return ResourceManager.GetString("ThemesInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose destinations based on the kind of experience you want to have. This view helps you explore places that match your travel mood and expectations..
        /// </summary>
        public static string ThemesInterestsDesc {
            get {
                return ResourceManager.GetString("ThemesInterestsDesc", resourceCulture);
            }
        }
    }
}
