//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeoTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeoTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.WEB.Resources.SeoTranslations", typeof(SeoTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore countries and cities, learn interesting facts, and create your profile to find destinations that match your lifestyle, whether for a trip or a new home..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the Best Cities and Countries to Live or Travel.
        /// </summary>
        public static string AppIndexTitle {
            get {
                return ResourceManager.GetString("AppIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Destinations.
        /// </summary>
        public static string BestDestinations {
            get {
                return ResourceManager.GetString("BestDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive selection from My Next Spot (based on dozens of different indexes and scores).
        /// </summary>
        public static string BestDestinationsDesc {
            get {
                return ResourceManager.GetString("BestDestinationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of Living.
        /// </summary>
        public static string CostLiving {
            get {
                return ResourceManager.GetString("CostLiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        public static string Economy {
            get {
                return ResourceManager.GetString("Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the economic aspects of the country, including income levels, inequality, economic freedom, and overall GDP metrics. These indicators help to understand the financial health and opportunities within the nation..
        /// </summary>
        public static string EconomyDesc {
            get {
                return ResourceManager.GetString("EconomyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment and Health.
        /// </summary>
        public static string EnvironmentHealth {
            get {
                return ResourceManager.GetString("EnvironmentHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the environmental and health aspects of the country, including air quality, water quality, pollution levels, and overall environmental performance. These metrics help to understand the ecological health and sustainability efforts within the nation..
        /// </summary>
        public static string EnvironmentHealthDesc {
            get {
                return ResourceManager.GetString("EnvironmentHealthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and Festivals.
        /// </summary>
        public static string EventsFestivals {
            get {
                return ResourceManager.GetString("EventsFestivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover destinations through their events and festivals. Plan your trips around cultural experiences, seasonal celebrations, and local happenings..
        /// </summary>
        public static string EventsFestivalsDesc {
            get {
                return ResourceManager.GetString("EventsFestivalsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover all countries on My Next Spot with their unique global scores, providing a clear overview of safety, economy, environment, and travel potential..
        /// </summary>
        public static string ExploreDesc {
            get {
                return ResourceManager.GetString("ExploreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        public static string HelpCenter {
            get {
                return ResourceManager.GetString("HelpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get detailed guides, troubleshooting tips, FAQs, and contact support for {0}. Solve issues and discover features easily..
        /// </summary>
        public static string HelpCenterDesc {
            get {
                return ResourceManager.GetString("HelpCenterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility and Tourism.
        /// </summary>
        public static string MobilityTourism {
            get {
                return ResourceManager.GetString("MobilityTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the mobility and tourism aspects of the country, including visa-free access, international arrivals, and overall travel friendliness. These indicators help to understand the ease of movement and attractiveness of the nation as a travel destination..
        /// </summary>
        public static string MobilityTourismDesc {
            get {
                return ResourceManager.GetString("MobilityTourismDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Suggestions.
        /// </summary>
        public static string MySuggestions {
            get {
                return ResourceManager.GetString("MySuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Holidays.
        /// </summary>
        public static string NationalHolidays {
            get {
                return ResourceManager.GetString("NationalHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Holidays in {0}.
        /// </summary>
        public static string NationalHolidaysIn {
            get {
                return ResourceManager.GetString("NationalHolidaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Destinations.
        /// </summary>
        public static string NextDestinations {
            get {
                return ResourceManager.GetString("NextDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores and Indexes.
        /// </summary>
        public static string ScoresIndexes {
            get {
                return ResourceManager.GetString("ScoresIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare destinations using global scores and indexes. Explore rankings and metrics to evaluate safety, economy, environment, and travel factors..
        /// </summary>
        public static string ScoresIndexesDesc {
            get {
                return ResourceManager.GetString("ScoresIndexesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security and Peace.
        /// </summary>
        public static string SecurityPeace {
            get {
                return ResourceManager.GetString("SecurityPeace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the security and peace aspects of the country, including public safety, crime perception, terrorism impact, and overall peacefulness. These indicators help to understand the stability and level of personal and national security within the nation..
        /// </summary>
        public static string SecurityPeaceDesc {
            get {
                return ResourceManager.GetString("SecurityPeaceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society and Government.
        /// </summary>
        public static string SocietyGovernment {
            get {
                return ResourceManager.GetString("SocietyGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the societal and governmental aspects of the country, including corruption levels, human development, democracy indices, freedom of expression, and overall happiness. These metrics help to understand the quality of governance and social well-being in the nation..
        /// </summary>
        public static string SocietyGovernmentDesc {
            get {
                return ResourceManager.GetString("SocietyGovernmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover travel suggestions on My Next Spot based on themes, interests, events, and destination scores to help you find your next ideal destination..
        /// </summary>
        public static string SuggestionsDesc {
            get {
                return ResourceManager.GetString("SuggestionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes and Interests.
        /// </summary>
        public static string ThemesInterests {
            get {
                return ResourceManager.GetString("ThemesInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose destinations based on the kind of experience you want to have. This view helps you explore places that match your travel mood and expectations..
        /// </summary>
        public static string ThemesInterestsDesc {
            get {
                return ResourceManager.GetString("ThemesInterestsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel History.
        /// </summary>
        public static string TravelHistory {
            get {
                return ResourceManager.GetString("TravelHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
    }
}
