//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.WEB.Translations.Module {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Country {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Country() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.WEB.Translations.Module.Country", typeof(Country).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts and geopolitical risks affecting this region.
        /// </summary>
        internal static string ConflictsDescription {
            get {
                return ResourceManager.GetString("ConflictsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts Overview.
        /// </summary>
        internal static string ConflictsOverview {
            get {
                return ResourceManager.GetString("ConflictsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        internal static string CurrentMonth {
            get {
                return ResourceManager.GetString("CurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        internal static string Economy {
            get {
                return ResourceManager.GetString("Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the economic aspects of the country, including income levels, inequality, economic freedom, and overall GDP metrics. These indicators help to understand the financial health and opportunities within the nation..
        /// </summary>
        internal static string EconomyDesc {
            get {
                return ResourceManager.GetString("EconomyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment and Health.
        /// </summary>
        internal static string EnvironmentHealth {
            get {
                return ResourceManager.GetString("EnvironmentHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the environmental and health aspects of the country, including air quality, water quality, pollution levels, and overall environmental performance. These metrics help to understand the ecological health and sustainability efforts within the nation..
        /// </summary>
        internal static string EnvironmentHealthDesc {
            get {
                return ResourceManager.GetString("EnvironmentHealthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Score.
        /// </summary>
        internal static string ExpensesScore {
            get {
                return ResourceManager.GetString("ExpensesScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels Like.
        /// </summary>
        internal static string FeelsLike {
            get {
                return ResourceManager.GetString("FeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Score.
        /// </summary>
        internal static string GlobalScore {
            get {
                return ResourceManager.GetString("GlobalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly lifestyle.
        /// </summary>
        internal static string Lifestyle {
            get {
                return ResourceManager.GetString("Lifestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe (it depends on your passport).
        /// </summary>
        internal static string MaybeRequirement {
            get {
                return ResourceManager.GetString("MaybeRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility and Tourism.
        /// </summary>
        internal static string MobilityTourism {
            get {
                return ResourceManager.GetString("MobilityTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the mobility and tourism aspects of the country, including visa-free access, international arrivals, and overall travel friendliness. These indicators help to understand the ease of movement and attractiveness of the nation as a travel destination..
        /// </summary>
        internal static string MobilityTourismDesc {
            get {
                return ResourceManager.GetString("MobilityTourismDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Holidays.
        /// </summary>
        internal static string NationalHolidays {
            get {
                return ResourceManager.GetString("NationalHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global holidays calendar with categorized events by type.
        /// </summary>
        internal static string NationalHolidaysDesc {
            get {
                return ResourceManager.GetString("NationalHolidaysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover global holidays organized by type, including national, religious, observance and optional events with clear visual categorization for planning..
        /// </summary>
        internal static string NationalHolidaysDescLong {
            get {
                return ResourceManager.GetString("NationalHolidaysDescLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Holidays in {0}.
        /// </summary>
        internal static string NationalHolidaysIn {
            get {
                return ResourceManager.GetString("NationalHolidaysIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        internal static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Score.
        /// </summary>
        internal static string SafetyScore {
            get {
                return ResourceManager.GetString("SafetyScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        internal static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores and Indexes.
        /// </summary>
        internal static string ScoresIndexes {
            get {
                return ResourceManager.GetString("ScoresIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare destinations using global scores and indexes. Explore rankings and metrics to evaluate safety, economy, environment, and travel factors..
        /// </summary>
        internal static string ScoresIndexesDesc {
            get {
                return ResourceManager.GetString("ScoresIndexesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security and Peace.
        /// </summary>
        internal static string SecurityPeace {
            get {
                return ResourceManager.GetString("SecurityPeace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the security and peace aspects of the country, including public safety, crime perception, terrorism impact, and overall peacefulness. These indicators help to understand the stability and level of personal and national security within the nation..
        /// </summary>
        internal static string SecurityPeaceDesc {
            get {
                return ResourceManager.GetString("SecurityPeaceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society and Government.
        /// </summary>
        internal static string SocietyGovernment {
            get {
                return ResourceManager.GetString("SocietyGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section provides insights into the societal and governmental aspects of the country, including corruption levels, human development, democracy indices, freedom of expression, and overall happiness. These metrics help to understand the quality of governance and social well-being in the nation..
        /// </summary>
        internal static string SocietyGovernmentDesc {
            get {
                return ResourceManager.GetString("SocietyGovernmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
