//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.WEB.Translations.Module {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.WEB.Translations.Module.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language.
        /// </summary>
        internal static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translates the app interface. Partial translations may apply for some languages..
        /// </summary>
        internal static string AppLanguageDesc {
            get {
                return ResourceManager.GetString("AppLanguageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        internal static string AppTheme {
            get {
                return ResourceManager.GetString("AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the App.
        /// </summary>
        internal static string GetTheApp {
            get {
                return ResourceManager.GetString("GetTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        internal static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More from DRMA Tech.
        /// </summary>
        internal static string MorefromDRMATech {
            get {
                return ResourceManager.GetString("MorefromDRMATech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover countries and cities around the globe, compare destinations, and uncover key facts for travel or relocation decisions..
        /// </summary>
        internal static string Step1Subtitle {
            get {
                return ResourceManager.GetString("Step1Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the world with clarity..
        /// </summary>
        internal static string Step1Title {
            get {
                return ResourceManager.GetString("Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze destinations based on lifestyle preferences, cost factors, visa requirements, and essential data, all in one place..
        /// </summary>
        internal static string Step2Subtitle {
            get {
                return ResourceManager.GetString("Step2Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare what matters..
        /// </summary>
        internal static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize past and future trips, save destinations, and build personalized travel plans tailored to your profile..
        /// </summary>
        internal static string Step3Subtitle {
            get {
                return ResourceManager.GetString("Step3Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan with confidence..
        /// </summary>
        internal static string Step3Title {
            get {
                return ResourceManager.GetString("Step3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account to access destination matching, saved trips, and personalized recommendations..
        /// </summary>
        internal static string Step4Subtitle {
            get {
                return ResourceManager.GetString("Step4Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock your global profile..
        /// </summary>
        internal static string Step4Title {
            get {
                return ResourceManager.GetString("Step4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        internal static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app and share it with your friends!.
        /// </summary>
        internal static string WriteReviewSubtitle {
            get {
                return ResourceManager.GetString("WriteReviewSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help {0} grow!.
        /// </summary>
        internal static string WriteReviewTitle {
            get {
                return ResourceManager.GetString("WriteReviewTitle", resourceCulture);
            }
        }
    }
}
