//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.WEB.Translations.Module {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Suggestion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Suggestion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NS.WEB.Translations.Module.Suggestion", typeof(Suggestion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Connectivity.
        /// </summary>
        public static string AirConnectivityIndex {
            get {
                return ResourceManager.GetString("AirConnectivityIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Quality.
        /// </summary>
        public static string AirQuality {
            get {
                return ResourceManager.GetString("AirQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Temperature.
        /// </summary>
        public static string AnnualTemperature {
            get {
                return ResourceManager.GetString("AnnualTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Censorship.
        /// </summary>
        public static string CensorshipIndex {
            get {
                return ResourceManager.GetString("CensorshipIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corruption Perceptions.
        /// </summary>
        public static string CorruptionScore {
            get {
                return ResourceManager.GetString("CorruptionScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality of Democracy.
        /// </summary>
        public static string DMDemocracyIndex {
            get {
                return ResourceManager.GetString("DMDemocracyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic Freedom.
        /// </summary>
        public static string EconomicFreedomIndex {
            get {
                return ResourceManager.GetString("EconomicFreedomIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Democracy Index.
        /// </summary>
        public static string EconomistDemocracyIndex {
            get {
                return ResourceManager.GetString("EconomistDemocracyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freedom of Expression.
        /// </summary>
        public static string FreedomExpressionIndex {
            get {
                return ResourceManager.GetString("FreedomExpressionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freedom in the World.
        /// </summary>
        public static string FreedomScore {
            get {
                return ResourceManager.GetString("FreedomScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDP (Nominal).
        /// </summary>
        public static string GDP_Nominal {
            get {
                return ResourceManager.GetString("GDP_Nominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDP (PPP).
        /// </summary>
        public static string GDP_PPP {
            get {
                return ResourceManager.GetString("GDP_PPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Peace.
        /// </summary>
        public static string GlobalPeaceIndex {
            get {
                return ResourceManager.GetString("GlobalPeaceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Terrorism.
        /// </summary>
        public static string GlobalTerrorismIndex {
            get {
                return ResourceManager.GetString("GlobalTerrorismIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Happiness.
        /// </summary>
        public static string HappinessIndex {
            get {
                return ResourceManager.GetString("HappinessIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDI.
        /// </summary>
        public static string HDI {
            get {
                return ResourceManager.GetString("HDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Care.
        /// </summary>
        public static string HealthCareIndex {
            get {
                return ResourceManager.GetString("HealthCareIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution.
        /// </summary>
        public static string NumbeoPollutionIndex {
            get {
                return ResourceManager.GetString("NumbeoPollutionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety (Numbeo).
        /// </summary>
        public static string NumbeoSafetyIndex {
            get {
                return ResourceManager.GetString("NumbeoSafetyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OECD.
        /// </summary>
        public static string OECD {
            get {
                return ResourceManager.GetString("OECD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainable Mobility.
        /// </summary>
        public static string SustainableMobilityIndex {
            get {
                return ResourceManager.GetString("SustainableMobilityIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourism.
        /// </summary>
        public static string TourismIndex {
            get {
                return ResourceManager.GetString("TourismIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety (TSA).
        /// </summary>
        public static string TsaSafetyIndex {
            get {
                return ResourceManager.GetString("TsaSafetyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string VisaFree {
            get {
                return ResourceManager.GetString("VisaFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitation / Water.
        /// </summary>
        public static string YaleWaterScore {
            get {
                return ResourceManager.GetString("YaleWaterScore", resourceCulture);
            }
        }
    }
}
